### ISSUE TITLE
contributing content

### ISSUE THREAD

**Issue by ergodicbreak** [durkdev/DROP#11]
hello! @j3b4 and I chatted in the Evennia discord and I offered to contribute writing to DROP. I don't know how you all want to keep track of this sort of thing but I thought this issue could be the place, or we could do something else and/or figure it out here. 

If this issue is a good place, how do you want to get started? @j3b4 suggested encounter dialog and actions for mobs.

**Comment by j3b4** [comment]
Hi @ergodicbreak,  I can think of two steps to take off the bat.
1. I'll create a directory called "creative" that will form part of the main repo and be under the same licence. (Have we chosen a licence yet?)   Into that folder anyone can create new plain or markdown text documents any time about anything at all.  So you can drop creative writing in there at any time.

2. When I (or anyone else) has a particular need for narrative or descriptive content we can create an issue requesting it using the github issue feature (like we are now). Then anyone can accept the writing prompt by composing the requested content and adding it to the creative folder.

**Comment by ergodicbreak** [comment]
Sounds good! I like thinking of it as a writing prompt. Keeping the prompts to manageable chunks (say, 5-10 descs, dialogs, etc.) would be good -- this worked well once on another project where we collaborated using some forum software.
